---
driver_plugin: vagrant
platforms:
- name: ubuntu-10.04
  driver_config:
    box: opscode-ubuntu-10.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-ubuntu-10.04.box
  run_list:
  - recipe[apt]
# - name: ubuntu-12.04
#   driver_config:
#     box: opscode-ubuntu-12.04
#     box_url: https://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-ubuntu-12.04.box
#   run_list:
#   - recipe[apt]
suites:
- name: default
  run_list:
  - recipe[opscode-dev-shim]
  - recipe[opscode-authz]
  - recipe[opscode-authz::database_test]
  attributes:
    postgresql:
      password:
        postgres: honeybadger
